---
title: "Minh Chau"
author: Minh Chau
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ["resume", "custom.css"]
    self_contained: true
---



Aside
================================================================================

<div style="margin-top:-40px;">
Contact {#contact}
--------------------------------------------------------------------------------

 <i class="fa fa-envelope" style ="margin-left:2px;margin-right:2px;margin-bottom:6px;color:#8db2ef;"></i> [minh.chau@outlook.co.nz](mailto:minh.chau@outlook.co.nz)
 <br>
 <i class="fa fa-phone" style ="margin-left:2px;margin-right:3px;color:#8db2ef;"></i><span style="font-weight:400; color:black;">*+64-22-036-1978*</span><br>
 <i class="fa fa-github" style ="margin-left:2px;margin-top:5px;margin-right:3px;color:#8db2ef;"></i>[Github profile](https://github.com/MinhChauVanNguyen)<br>
 <i class="fa fa-home" style ="margin-left:2px;margin-top:5px;margin-right:2px;color:#8db2ef;"></i>[Personal website](https://minhchauvannguyen.github.io/)<br>
 <i class="fa fa-linkedin" style ="margin-left:2.5px;margin-top:5px;margin-right:2px;color:#8db2ef;"></i> [Linkedin](https://www.linkedin.com/in/minh-chau-van/)<br>

</div>


Key Skills {#skills}
--------------------------------------------------------------------------------
<div style="margin-bottom:20px;"></div>
<div class="container">
  <div class="skills">Communication and writing skills</div>
</div>


<div class="container">
  <div class="skills">Adapt quickly to new systems and computer competences</div>
</div>

<div class="container">
  <div class="skills">Experience with data entry and reporting </div>
</div>

<div class="container">
  <div class="skills">Good understanding of data <br> privacy principles</div>
</div>

<div class="container">
  <div class="skills">Strong attentition-to-detail and <br> customer service skills</div>
</div>

<div class="container">
  <div class="skills">Advanced Microsoft Word, Power Point and Excel skills</div>
</div>

<div class="container">
  <div class="skills">Ability to keep track of input and processing activities to ensure data consistency</div>
</div>



References {#packages}
--------------------------------------------------------------------------------
<div style="margin-top:10px;">
</div>
<span style="color:#8db2ef;">❑</span> **Shirley Wu**
<div style="margin-left:14px;margin-top:-10px;">
Operations Manager </br>
Harmonic Analytics </br>
[shirley@harmonic.co.nz](mailto:shirley@harmonic.co.nz) <br>
</div>
   <span style="color:#8db2ef;">❑</span> **Ploi Yibmantasiri**
<div style="margin-left:14px;margin-top:-10px;">
Data Scientist </br>
Harmonic Analytics </br>
[ploi@harmonic.co.nz](mailto:ploi@harmonic.co.nz)
</div>








Main
================================================================================

<span style="font-family:Graphik, sans serif !important;color:#8db2ef;font-weight:bold;">Minh Chau</span> {#title}
--------------------------------------------------------------------------------
<span style="color:black;font-size:12.5px;"> As a recently graduated university student with excellent logical thinking and organisational skills, I am currently seeking a job opportunity in the data maintaining and information processing field to expand my professional experience within the workforce. </span>



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Master of Applied Statistics

<span>Victoria University of Wellington</span>

<span>Wellington, NZ</span>

03/2019 - 06/2020

### Bachelor of Science in Statistics

<span>Otago University</span>

<span>Dunedin, NZ</span>

03/2015 - 06/2018


<div style = "margin-top:20px;"></div>


Work Experience {data-icon=black-tie}
--------------------------------------------------------------------------------

### Research Assistant

<span>Massey University Wellington</span>

<span>Wellington, NZ</span>

<div style = "margin-top:20px;">

 - Communicate with the client clearly to fulfil requirements
 - Prepare and transform survey data for analytical purposes
 - Create informative graphs and tables to present key findings
 - Apply statistical methods to data and produce insightful interpretations in plain English
</div>

08/2020 - current

<div style = "margin-top:20px;"></div>


### Sessional Assistant

<span>Victoria University of Wellington</span>

<span>Wellington, NZ</span>

<div style = "margin-top:20px;">

 - Mark 100-level statistics assignments and projects
 - Attend to training and meetings
 - Enter assignment grades correctly and in accordance with the marking system's guidelines
</div>

04/2020 - current

<div style = "margin-top:20px;"></div>

### Intern/Data Analyst

<span>Harmonic Analytics</span>

<span>Wellington, NZ</span>

<div style="margin-top:20px;">

 - Extract,transform and analyse time series data to draw appropriate interpretations and conclusions
 - Construct time series models to make monthly and yearly predictions
 - Produce an interactive Shiny dashboard to present predictive techniques and significant statistical results
 - Co-operate with supervisor and manager to deliver according to the client’s requirements and ensure data quality is optimised


</div>

03/2020 - 06/2020

<div style = "margin-bottom:30px;"></div>



:::{.aside style="top:880px;"}
*This resume was made with the R package <span style ="color:#8db2ef;font-weight:bold;">pagedown</span>*.
:::

```{r echo = FALSE,eval = FALSE}
pagedown::chrome_print('~/Documents/Resume/Data_entry.html')
```
