---
title: "Minh Chau"
author: Minh Chau
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ["resume", "custom.css"]
    self_contained: true
---



Aside
================================================================================

<div style="margin-top:-40px;">
Contact {#contact}
--------------------------------------------------------------------------------

 <i class="fa fa-envelope" style ="margin-left:2px;margin-right:2px;margin-bottom:6px;color:#8db2ef;"></i> [minh.chau@outlook.co.nz](mailto:minh.chau@outlook.co.nz)
 <br>
 <i class="fa fa-phone" style ="margin-left:2px;margin-right:3px;color:#8db2ef;"></i><span style="font-weight:400; color:black;">*+64-22-036-1978*</span><br>
 <i class="fa fa-github" style ="margin-left:2px;margin-top:5px;margin-right:3px;color:#8db2ef;"></i>[Github profile](https://github.com/MinhChauVanNguyen)<br>
 <i class="fa fa-home" style ="margin-left:2px;margin-top:5px;margin-right:2px;color:#8db2ef;"></i>[Personal website](https://minhchauvannguyen.github.io/)<br>
 <i class="fa fa-linkedin" style ="margin-left:2.5px;margin-top:5px;margin-right:2px;color:#8db2ef;"></i> [Linkedin](https://www.linkedin.com/in/minh-chau-van/)<br>

</div>

Packages {#packages}
--------------------------------------------------------------------------------
<div style="margin-top:10px;">
</div>
**Statistical Programming:** <br>
   <span style="margin-left:10px;color:#8db2ef;">❑</span> Experience with R  <br>
   <span style="margin-left:10px;color:#8db2ef;">❑</span> Exposure to SAS, SPSS, SQL</span> <br>
<div style = "margin-bottom:3px;"></div>
**Web development:**  HTML, CSS <br>
<div style = "margin-bottom:3px;"></div>
**Machine learning:** Python<br>
<div style = "margin-bottom:3px;"></div>
**Reporting:** R Markdown, Latex<br>
<div style = "margin-bottom:3px;"></div>
**Data Visualisation:** Shiny, Flexdashboard, Dash<br>
<div style = "margin-bottom:3px;"></div>
**Workflow:** Github, Gitlab<br>
<div style = "margin-bottom:3px;"></div>
**MS Office:** Excel (Analysis TookPak), Power Point, Word<br>
<div style = "margin-bottom:3px;"></div>



Strengths {#skills}
--------------------------------------------------------------------------------
<div style="margin-bottom:20px;"></div>
<div class="container">
  <div class="skills">Good understanding of predictive forecasting and classification <br> models<br> </div>
</div>

<div class="container">
  <div class="skills">Build and maintain professional work relationships</div>
</div>

<div class="container">
  <div class="skills">Analytical thinking and problem-solving skills</div>
</div>

<div class="container">
  <div class="skills">Advanced data wrangling <br> techniques, statistical inference and probability distributions</div>
</div>

<div class="container">
  <div class="skills">Experience with analysing and <br> interpreting qualitative and <br> quantitative data</div>
</div>




Main
================================================================================

<span style="font-family:Graphik, sans serif !important;color:#8db2ef;font-weight:bold;">Minh Chau</span> {#title}
--------------------------------------------------------------------------------
<span style="color:black;font-size:12.5px;">I am a hard-working and accountable graduate with more than two years experience using statistical analysis and reporting software. I am seeking employment that will enhance my profession as a Data Analyst in producing reliable statistics, and thus contribute to New Zealand society.</span>


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Master of Applied Statistics

<span>Victoria University of Wellington</span>

<span>Wellington, NZ</span>

03/2019 - 06/2020

### Bachelor of Science in Statistics

<span>Otago University</span>

<span>Dunedin, NZ</span>

03/2015 - 06/2018


<div style = "margin-top:20px;"></div>


Work Experience {data-icon=black-tie}
--------------------------------------------------------------------------------

### Research Assistant

<span>Massey University Wellington</span>

<span>Wellington, NZ</span>

<div style = "margin-top:20px;">

 - Communicate with the client clearly to fulfil requirements 
 - Prepare and transform raw survey data for analytical purposes
 - Create informative graphs and tables to present key findings 
 - Analyse data using appropriate statistical methodologies in order to make insightful interpretations about the data 
</div>

08/2020 - current

<div style = "margin-top:20px;"></div>


### Sessional Assistant

<span>Victoria University of Wellington</span>

<span>Wellington, NZ</span>

<div style = "margin-top:20px;">

 - Mark 100-level statistics assignments and projects
 - Attend to training and meetings
 - Enter assignment grades correctly and in accordance with the marking system's guidelines
</div>

04/2020 - current

<div style = "margin-top:20px;"></div>

### Intern/Data Analyst

<span>Harmonic Analytics</span>

<span>Wellington, NZ</span>

<div style="margin-top:20px;">

 - Extract, transform and analyse time series data to draw <br> appropriate interpretations and conclusions
 - Construct time series models to make monthly and yearly predictions
 - Produce an interactive Shiny dashboard to present <br> predictive techniques and significant statistical results
 - Co-operate with supervisor and manager to deliver according to the client’s requirements and ensure data quality is optimised


</div>

03/2020 - 06/2020

<div style = "margin-bottom:30px;"></div>






Projects {data-icon=coffee}
--------------------------------------------------------------------------------

<div style="margin-left:65px;margin-bottom:10px;font-size:12px;">The following projects which can be found in details on my portfolio, [*https://minhchauvannguyen.github.io/*](https://minhchauvannguyen.github.io/), have helped me to develop and strengthen my analytical, programming and reporting outcomes abilities. </div>



### Statistical Consulting Project Assignment <span style="font-size:11px;float:right;">[Link](https://drive.google.com/file/d/1A8YgvAbl9w6mb4Auzjh-PVVr8fIwEoLc/view)</span><i class="fa fa-globe"></i>

<span style = "line-height:150%;">*Objective*</span> : Investigate the relationship between the amount of fish intake and mercury levels found in fisherman hair.<br><span style="background-color:rgba(141, 178, 239, 0.3);line-height:200%;">*Key skills learned*</span>

N/A

08/2019

-  Apply exploratory analysis to construct appropriate statistical models according to the nature of the data
 - Interpret outcomes of the methods implemented that are relevant and help answer to the report's goals and objectives


<div style="margin-bottom:10px;"></div>

### Cluster Analysis Research Project <span style="font-size:11px;float:right;">[Link](https://drive.google.com/file/d/1QBTAUTxXp_C3B6fx2Ah9_81BhHMoNgPf/view)</span><i class="fa fa-globe"></i>

<span style = "line-height:150%;">*Objective*</span> : Outline the research methods neccessary for the analysis of ordinal and binary lingustics data. <br><span style="background-color:rgba(141, 178, 239, 0.3);line-height:200%;">*Key skills learned*</span>

N/A

02/2020

 - Research clustering methods for analysing qualitative data
 - Construct and compare statistical models under theoretical framework

<div style='margin-bottom:10px;'></div>


### Time Series Analysis Shiny Dashboard <span style="font-size:11px;float:right;">[Link](https://minhchau.shinyapps.io/oranges/)</span><i class="fa fa-globe"></i>

<span style = "line-height:150%;">*Objective*</span> : Demonstrate time series analysis and predictive <br> modelling methods for data recorded at monthly interval. <br><span style="background-color:rgba(141, 178, 239, 0.3);line-height:200%;">*Key skills learned*</span>

N/A

06/2020

 - Design a Shiny dashboard consisting of interactive graphs and <br> tables to summarise the methods used and present the results
 - Emphasize important details of the dashboard to ensure it is user-friendly and appeals to a non-statistical audience


<div style="margin-bottom:10px;"></div>


### ICMR in Patients Under 18 years old Report <span style="font-size:11px;float:right;">[Link](https://drive.google.com/file/d/1_94PQm6wHnYZ_Qo5SaU1i92-ZkW2iqtc/view)</span><i class="fa fa-globe"></i>

<span style = "line-height:150%;">*Objective*</span> : Investigate potential relationships between features in the context of medical statistics. <br><span style="background-color:rgba(141, 178, 239, 0.3);line-height:200%;">*Key skills learned*</span>

N/A

09/2020

 - Generate a report to summarise different statistical techniques and their applications to health data 
 - Highlight and interpret key findings to answer to the research question and make comments towards future considerations


<div style="margin-bottom:10px;"></div>


### NZ Music Community Diversity Report<span style="font-size:11px;float:right;">[Link](https://apraamcos.com.au/media/19169/amplify-aotearoa-gender-diversity-report.pdf)</span><i class="fa fa-globe"></i>

<span style = "line-height:150%;">*Objective*</span>: Analyse gender discrimination and bias within the Aotearoa music community<br><span style="background-color:rgba(141, 178, 239, 0.3);line-height:200%;">*Key skills learned*</span>

N/A

11/2020

 - Report trends and patterns found in data that indicate an association between gender diversity and experience of discrimination
 - Produce graphs and tables from statistical findings to draw <br> evidence-based conclusions 

<div style="margin-bottom:20px;"></div>


:::{.aside style="top:5px;"}


<div style="font-size:17.6px;color:black;font-weight:400;">LANGUAGES</div>

<div style="margin-bottom:-4px;margin-top:15px;"><span style="color:#8db2ef;">❑ </span> Vietnamese (fluent)</div>
<span style="color:#8db2ef;">❑ </span> English (fluent) 

<div style="font-size:17.6px;color:black;font-weight:400;margin-top:60px;">REFERENCES</div>

<div style="margin-top:15px">
   <span style="color:#8db2ef;">❑</span> **Shirley Wu**</span><br>
   <span style="margin-left:14px;margin-top:-10px;">Operations Manager</span> <br>
   <span style="margin-left:14px;">Harmonic Analytics</span> 
    <span style="margin-left:14px;">[shirley@harmonic.co.nz](mailto:shirley@harmonic.co.nz)</span>
</div>

<div>
   <span style="color:#8db2ef;">❑</span> **Ploi Yibmantasiri** <br>
   <span style="margin-left:14px;margin-top:-10px;">Data Scientist</span> <br>
   <span style="margin-left:14px;">Harmonic Analytics</span>
   <span style="margin-left:14px;">[ploi@harmonic.co.nz](mailto:ploi@harmonic.co.nz)</span>
</div>

<div style="margin-bottom:500px;">
   <span style="color:#8db2ef;">❑</span> **Oli Wilson** <br>
   <span style="margin-left:14px;margin-top:-10px;">Associate Professor</span> <br>
   <span style="margin-left:14px;">College of Creative Arts</span> <br>
   <span style="margin-left:14px;">Massey University</span>
   <span style="margin-left:14px;">[o.wilson@massey.ac.nz](mailto:o.wilson@massey.ac.nz)</span>
</div>



*This resume was made with the R package <span style ="color:#8db2ef;font-weight:bold;">pagedown</span>*.


:::


```{r echo = FALSE,eval = FALSE}
pagedown::chrome_print('~/Documents/Resume/Minh_CV.html')
```
